server:
  port: 9090

ipserver: 127.0.0.1

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 1024MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/match?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    password: 123456
    username: root
    hikari:
      #连接池名
      pool-name:
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活时间
      idle-timeout: 1800000
      #最大连接数
      maximum-pool-size: 10
      # 从连接池返回的连接 自动提交
      auto-commit: true
      # 连接存在最长时间
      max-lifetime: 1800000
      # 连接超时时间
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  redis: #记得关linux防火墙
    host: 192.168.3.100
    port: 6379
    password: "258415"
    timeout: 50000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: 18000
        max-idle: 280
        min-idle: 5
  mail:
    username: 1409109706@qq.com
    password: vseunaclzmtcgjhc
    host: smtp.qq.com
    properties:
      mail:
        smtl:
          ssl:
            enable: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

alipay:
  appId: 2021000121628865
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZ1jbWki4ocDwSKXsWvAyGLgMLXkqwUl8vsGePQ7R2aWndYBaYX/ioROmpJd2a3wRzTeeIaxEYEycgkl2i85j0fAoXcR98iR028pMVcMql9HLxVhn1jI6lBGLp61tsEgxpvpJN9t0bPa2T77U5FTe+1+oNWMz4iGXY6swufJXjtOwg9s2ux1lX9Selm+uAZaWgVMXH/0sdbNvVCbXtAb++F6SoNM8MkNuAk1J50Ey/ACDhVgPDaCDn/ulZBGOpUBLw/IhyYRR5O9ewoBVjZGU2P5aChzBnaP85TZRNgYnI0Zwa9c3II/HdTKMoQj8S2buNF8VWpdReSL51SADfHWJ1AgMBAAECggEAfNJLfJ7vxPAMTdBKh4/duaHr5nWDtL2hblh8LsqIyuuNcopcyxZT9HS2AwEuZlM+kTBNBWuaWyZvQQaB4440NWvP5GVtXucCRWtd3K/APheyjA+I0KxTsaF1gMfvTij22XY/z/LWRRwukzKUoNSOftNCncHHzoEd4nvhYHbGSBNqtXff8xNtzi6tOoOt+wHLEIoP+4nXIeZvBVdeZ1Bj0cxua2TJ0WhPm5oA2TLh5+qfp1ZLVNw9iTKe/MOm5hYq37dZU8eOisJBP0gS3XPXQ4BeCo6C7j+ZnRJzNX3IG0kCNcXCX8qJYL/IPKahd4LPPQjsWIYo7tsbAVI8v1COAQKBgQDMaSwDmTHcBgeEpfWYGRwvfpTPi9r8/NDvxy7TDUGVEnIX2HpKGZwH4RLZy5VRKsroeOBaZ2nUlMiLzCW5j8FOT/bXMtu1SndR8QfCVIKK/jLJpXLICihBLQJVVxqBhU2omYqmhowPTy0xJK/XaztrLsQU1v1UihAqOyV/ZXLwkQKBgQDAqX28b7CFl7tcKpaIZ47BuQuPwwH6CL4KbFYwVMyhSCownFYDINq1pAALq/CszhxN2cbMAaR5DTt8ojttFf1zm0XjuXNpzSG+oClbPCRXvOx62qGmMbhno7W8F/FsWwDc52cb1FhU9prMuw5jqIWr1sv1+GLl8WUXf6pGir2FpQKBgFGOVMVKxh3nOfCu1oJM4nYApxb30fPGWwaQDhqe21/C8EqbUI9oEF0EbCUBmR29WR/PupPXVt4+TpWYaiTTOmkodm/+FrMKdvj2lgXu+fbC3TifDmDJzK3Ua23pRuYObaGrQSqX3CHvkTReUto8KoTlL86wyHqGa1SuLJPbwjRBAoGBAJYCYlhaToN2RPfaYSMMHudPgWUKXXulWvMar3EqVbouSktXLtF4v1I2w6JS2i5yvS8Qpe0qSjnGx86fMs4ZFSLyf1R0jRyQD/oxEoJrLZDzFN4DZWHVzNNFcLdnnR7VLLLTqkDM8YoWCSnna6jFCm9l66E1KSwI7MGDMb2DQVXRAoGAdC/cBws22w2JxyMVziZytRlC3bK8LAxiyIKY/2LUJJzQuNdDDngWHdYsM3X6K3lA+Fq/Va98nCm4nUlp2DZ1jJ2GE11Nzq5lrh8csRs75UDxJMK61OT1ec1EjjV2Uhge21IVacZD25k5He1No9Op9yMx2f/aNr05pGoODfXHYAQ=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlBYZ/XrOv+16+sUz2oJz4ruSKAYWK82J0BNgvDRWM/Xp4eQBmRXbmHNIyHsAKGBhgkm/OGqWAH1TW/CD3TVqUTYBsQu3WeCcCO7G0HjriZqMH4+7CAqJn/AhUqa1r08KdJxbWvKEwjbyOCYC6R6k4u8HGiXYf2bsctrNP0Xfmf57M8Y22J9hmOh0eKIzvzqi/vn1NcVRTh3JRxJiK1o7vMcWJxUQqH4FyXzy/5tn7e0NhPNNVRZ2k+y52IbyiWGdGiMS4zrnPedih5Ztsn9Sf2csHIW3jj/vDoRS/9uHC6MK1UaQZ+JZo/egFCTleqBCxwnHibyaFms3XNa6xdaGUQIDAQAB
  notifyUrl: http://5etigj.natappfree.cc/alipay/notify
#logging:
#  # 设置logback.xml位置
#  #  config: classpath:log/logback.xml
#  # 设置log4j.properties位置
#  config: classpath:log4j.properties
logging:
  level:
    com.example.demo.mapper: debug
  charset:
file:
  ip: 127.0.0.1